/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Chapter } from "../../chapter/base/Chapter";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsEnum,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { JsonValue } from "type-fest";
import { EnumComicGenres } from "./EnumComicGenres";
import { EnumComicStatus } from "./EnumComicStatus";
import { EnumComicTags } from "./EnumComicTags";

@ObjectType()
class Comic {
  @ApiProperty({
    required: false,
    type: () => [Chapter],
  })
  @ValidateNested()
  @Type(() => Chapter)
  @IsOptional()
  chapters?: Array<Chapter>;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  cover!: JsonValue;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    enum: EnumComicGenres,
    isArray: true,
  })
  @IsEnum(EnumComicGenres, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumComicGenres], {
    nullable: true,
  })
  genres?: Array<"Option1">;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    enum: EnumComicStatus,
  })
  @IsEnum(EnumComicStatus)
  @IsOptional()
  @Field(() => EnumComicStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  summary!: string | null;

  @ApiProperty({
    required: false,
    enum: EnumComicTags,
    isArray: true,
  })
  @IsEnum(EnumComicTags, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumComicTags], {
    nullable: true,
  })
  tags?: Array<"Option1">;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Comic as Comic };
