/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ComicService } from "../comic.service";
import { ComicCreateInput } from "./ComicCreateInput";
import { Comic } from "./Comic";
import { ComicFindManyArgs } from "./ComicFindManyArgs";
import { ComicWhereUniqueInput } from "./ComicWhereUniqueInput";
import { ComicUpdateInput } from "./ComicUpdateInput";
import { ChapterFindManyArgs } from "../../chapter/base/ChapterFindManyArgs";
import { Chapter } from "../../chapter/base/Chapter";
import { ChapterWhereUniqueInput } from "../../chapter/base/ChapterWhereUniqueInput";

export class ComicControllerBase {
  constructor(protected readonly service: ComicService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Comic })
  async createComic(@common.Body() data: ComicCreateInput): Promise<Comic> {
    return await this.service.createComic({
      data: data,
      select: {
        cover: true,
        createdAt: true,
        genres: true,
        id: true,
        status: true,
        summary: true,
        tags: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Comic] })
  @ApiNestedQuery(ComicFindManyArgs)
  async comics(@common.Req() request: Request): Promise<Comic[]> {
    const args = plainToClass(ComicFindManyArgs, request.query);
    return this.service.comics({
      ...args,
      select: {
        cover: true,
        createdAt: true,
        genres: true,
        id: true,
        status: true,
        summary: true,
        tags: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Comic })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async comic(
    @common.Param() params: ComicWhereUniqueInput
  ): Promise<Comic | null> {
    const result = await this.service.comic({
      where: params,
      select: {
        cover: true,
        createdAt: true,
        genres: true,
        id: true,
        status: true,
        summary: true,
        tags: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Comic })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateComic(
    @common.Param() params: ComicWhereUniqueInput,
    @common.Body() data: ComicUpdateInput
  ): Promise<Comic | null> {
    try {
      return await this.service.updateComic({
        where: params,
        data: data,
        select: {
          cover: true,
          createdAt: true,
          genres: true,
          id: true,
          status: true,
          summary: true,
          tags: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Comic })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteComic(
    @common.Param() params: ComicWhereUniqueInput
  ): Promise<Comic | null> {
    try {
      return await this.service.deleteComic({
        where: params,
        select: {
          cover: true,
          createdAt: true,
          genres: true,
          id: true,
          status: true,
          summary: true,
          tags: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/chapters")
  @ApiNestedQuery(ChapterFindManyArgs)
  async findChapters(
    @common.Req() request: Request,
    @common.Param() params: ComicWhereUniqueInput
  ): Promise<Chapter[]> {
    const query = plainToClass(ChapterFindManyArgs, request.query);
    const results = await this.service.findChapters(params.id, {
      ...query,
      select: {
        comic: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        images: true,
        numberField: true,
        releaseDate: true,
        thumbnail: true,
        title: true,
        updateDate: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/chapters")
  async connectChapters(
    @common.Param() params: ComicWhereUniqueInput,
    @common.Body() body: ChapterWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      chapters: {
        connect: body,
      },
    };
    await this.service.updateComic({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/chapters")
  async updateChapters(
    @common.Param() params: ComicWhereUniqueInput,
    @common.Body() body: ChapterWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      chapters: {
        set: body,
      },
    };
    await this.service.updateComic({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/chapters")
  async disconnectChapters(
    @common.Param() params: ComicWhereUniqueInput,
    @common.Body() body: ChapterWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      chapters: {
        disconnect: body,
      },
    };
    await this.service.updateComic({
      where: params,
      data,
      select: { id: true },
    });
  }
}
